// Auto-generated by tools/generate-assets.mjs
export interface AssetFrame {
  frame: number
  x: number
  y: number
  w: number
  h: number
}

export interface SpriteSheetAsset {
  path: string
  frames: number
  frameWidth: number
  frameHeight: number
  cols: number
  rows: number
  totalWidth: number
  totalHeight: number
  animations?: Record<string, [number, number]>
}

export interface ImageAsset {
  path: string
  width: number
  height: number
}

export interface AssetManifest {
  weapons: Record<string, SpriteSheetAsset>
  support: Record<string, SpriteSheetAsset>
  backgrounds: Record<string, ImageAsset>
  ui: Record<string, ImageAsset>
}

export const assetManifest: AssetManifest = {
  "weapons": {
    "laser-beam": {
      "path": "assets/weapons/laser-beam.png",
      "frames": 3,
      "frameWidth": 32,
      "frameHeight": 8,
      "cols": 3,
      "rows": 1,
      "totalWidth": 96,
      "totalHeight": 8
    },
    "precision-laser": {
      "path": "assets/weapons/precision-laser.png",
      "frames": 3,
      "frameWidth": 16,
      "frameHeight": 4,
      "cols": 3,
      "rows": 1,
      "totalWidth": 48,
      "totalHeight": 4
    },
    "heavy-laser": {
      "path": "assets/weapons/heavy-laser.png",
      "frames": 3,
      "frameWidth": 48,
      "frameHeight": 12,
      "cols": 3,
      "rows": 1,
      "totalWidth": 144,
      "totalHeight": 12
    },
    "missile": {
      "path": "assets/weapons/missile.png",
      "frames": 4,
      "frameWidth": 16,
      "frameHeight": 8,
      "cols": 4,
      "rows": 1,
      "totalWidth": 64,
      "totalHeight": 8
    },
    "homing-missile": {
      "path": "assets/weapons/homing-missile.png",
      "frames": 4,
      "frameWidth": 16,
      "frameHeight": 8,
      "cols": 4,
      "rows": 1,
      "totalWidth": 64,
      "totalHeight": 8
    },
    "cluster-missile": {
      "path": "assets/weapons/cluster-missile.png",
      "frames": 3,
      "frameWidth": 24,
      "frameHeight": 8,
      "cols": 3,
      "rows": 1,
      "totalWidth": 72,
      "totalHeight": 8
    },
    "bullet": {
      "path": "assets/weapons/bullet.png",
      "frames": 2,
      "frameWidth": 8,
      "frameHeight": 4,
      "cols": 2,
      "rows": 1,
      "totalWidth": 16,
      "totalHeight": 4
    },
    "heavy-mg-bullet": {
      "path": "assets/weapons/heavy-mg-bullet.png",
      "frames": 2,
      "frameWidth": 12,
      "frameHeight": 6,
      "cols": 2,
      "rows": 1,
      "totalWidth": 24,
      "totalHeight": 6
    },
    "artillery-shell": {
      "path": "assets/weapons/artillery-shell.png",
      "frames": 4,
      "frameWidth": 24,
      "frameHeight": 12,
      "cols": 4,
      "rows": 1,
      "totalWidth": 96,
      "totalHeight": 12
    },
    "heavy-artillery": {
      "path": "assets/weapons/heavy-artillery.png",
      "frames": 4,
      "frameWidth": 32,
      "frameHeight": 16,
      "cols": 4,
      "rows": 1,
      "totalWidth": 128,
      "totalHeight": 16
    },
    "explosion": {
      "path": "assets/weapons/explosion.png",
      "frames": 6,
      "frameWidth": 48,
      "frameHeight": 48,
      "cols": 6,
      "rows": 1,
      "totalWidth": 288,
      "totalHeight": 48
    },
    "shield-hit": {
      "path": "assets/weapons/shield-hit.png",
      "frames": 3,
      "frameWidth": 32,
      "frameHeight": 32,
      "cols": 3,
      "rows": 1,
      "totalWidth": 96,
      "totalHeight": 32
    }
  },
  "support": {
    "assault-tank": {
      "path": "assets/support/assault-tank.png",
      "frames": 8,
      "frameWidth": 48,
      "frameHeight": 24,
      "cols": 8,
      "rows": 1,
      "totalWidth": 384,
      "totalHeight": 24,
      "animations": {
        "idle": [
          0,
          3
        ],
        "fire": [
          4,
          7
        ]
      }
    },
    "defense-tank": {
      "path": "assets/support/defense-tank.png",
      "frames": 8,
      "frameWidth": 48,
      "frameHeight": 24,
      "cols": 8,
      "rows": 1,
      "totalWidth": 384,
      "totalHeight": 24,
      "animations": {
        "idle": [
          0,
          3
        ],
        "fire": [
          4,
          7
        ]
      }
    },
    "scout-drone": {
      "path": "assets/support/scout-drone.png",
      "frames": 8,
      "frameWidth": 32,
      "frameHeight": 32,
      "cols": 8,
      "rows": 1,
      "totalWidth": 256,
      "totalHeight": 32,
      "animations": {
        "hover": [
          0,
          3
        ],
        "fire": [
          4,
          7
        ]
      }
    }
  },
  "backgrounds": {
    "neon-city_far": {
      "path": "assets/backgrounds/neon-city_far.png",
      "width": 2048,
      "height": 768
    },
    "neon-city_near": {
      "path": "assets/backgrounds/neon-city_near.png",
      "width": 2048,
      "height": 768
    },
    "industrial_far": {
      "path": "assets/backgrounds/industrial_far.png",
      "width": 2048,
      "height": 768
    },
    "industrial_near": {
      "path": "assets/backgrounds/industrial_near.png",
      "width": 2048,
      "height": 768
    }
  },
  "ui": {
    "health-bar-frame": {
      "path": "assets/ui/health-bar-frame.png",
      "width": 256,
      "height": 32
    },
    "health-bar-fill-green": {
      "path": "assets/ui/health-bar-fill-green.png",
      "width": 256,
      "height": 32
    },
    "health-bar-fill-red": {
      "path": "assets/ui/health-bar-fill-red.png",
      "width": 256,
      "height": 32
    },
    "shield-bar-fill-blue": {
      "path": "assets/ui/shield-bar-fill-blue.png",
      "width": 256,
      "height": 32
    },
    "icon-armour": {
      "path": "assets/ui/icon-armour.png",
      "width": 32,
      "height": 32
    },
    "icon-shields": {
      "path": "assets/ui/icon-shields.png",
      "width": 32,
      "height": 32
    },
    "icon-weapons": {
      "path": "assets/ui/icon-weapons.png",
      "width": 32,
      "height": 32
    },
    "icon-targeting": {
      "path": "assets/ui/icon-targeting.png",
      "width": 32,
      "height": 32
    },
    "icon-nano-repair": {
      "path": "assets/ui/icon-nano-repair.png",
      "width": 32,
      "height": 32
    },
    "icon-legs": {
      "path": "assets/ui/icon-legs.png",
      "width": 32,
      "height": 32
    },
    "icon-coin": {
      "path": "assets/ui/icon-coin.png",
      "width": 32,
      "height": 32
    },
    "btn-primary": {
      "path": "assets/ui/btn-primary.png",
      "width": 64,
      "height": 32
    },
    "btn-secondary": {
      "path": "assets/ui/btn-secondary.png",
      "width": 64,
      "height": 32
    },
    "joystick-base": {
      "path": "assets/ui/joystick-base.png",
      "width": 128,
      "height": 128
    },
    "joystick-knob": {
      "path": "assets/ui/joystick-knob.png",
      "width": 48,
      "height": 48
    },
    "icon-192": {
      "path": "assets/ui/icon-192.png",
      "width": 192,
      "height": 192
    },
    "icon-512": {
      "path": "assets/ui/icon-512.png",
      "width": 512,
      "height": 512
    }
  }
}
